.TH sdbroker-monitor 8 "18 Mar 2014" "sdbroker-monitor" "Supportconfig Analysis Manual"
.SH NAME
sdbroker-monitor - SCA Broker Monitor
.SH SYNOPSIS
sdbroker-monitor
.SH DESCRIPTION
Confirms each agent is responding. Unresponsive agents are marked dead. Dead agents are reactivated with they become responsive.
.SH OPTIONS
.TP
None
.SH AUTHOR
Jason Record <jrecord@suse.com>
.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 of the License.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.
.SH SEE ALSO
.BR sdagent-config (8)

